// mario-app-deployment Jenkinsfile for deploying the Mario application to Kubernetes
pipeline {
    agent any

    environment {
        KUBE_CONFIG = 'k8s-config-id'
    }

    // Checkout the git repo in our feature branch to get the k8s manifest files for deployment
    stages {
        stage('Checkout') {
            steps {
                git branch: 'feature/jenkins-integration', url: 'https://github.com/bus57790/k8s-mario.git'
            }
        }

        // Checks the k8s manifest files for syntax errors and best practices using kubeconform
        stage('K8s Manifest Lint') {
            steps {
                script {
                    sh 'kubeconform -strict -summary k8s/deployment.yaml k8s/service.yaml'
                    // sh "kubectl apply --dry-run=client -f k8s/deployment.yaml --kubeconfig=${KUBE_CONFIG}"
                }
            }
        }

        // Deploys the application to Kubernetes using kubectl apply with the provided kubeconfig credentials
        stage('Deploy to Kubernetes') {
            steps {
                script {
                    withKubeConfig([credentialsId: env.KUBE_CONFIG]) {
                        sh """
                        kubectl apply -f k8s/deployment.yaml
                        kubectl apply -f k8s/service.yaml
                        """
                        // sed -i 's|image:.*|image: ${DOCKER_IMAGE}:${IMAGE_TAG}|g' k8s/deployment.yaml
                        // kubectl set image -f k8s/deployment.yaml mario=${DOCKER_IMAGE}:${IMAGE_TAG}
                    }
                }
            }
        }

        // Verifies the deployment by checking the rollout status and listing the pods in the mario namespace
        stage('Verify Deployment') {
            steps {
                script {
                    withKubeConfig([credentialsId: env.KUBE_CONFIG]) {
                        sh """
                        kubectl rollout status deployment/mario-deployment
                        kubectl get pods -l app=mario
                        """
                    }
                }
            }
        }
    }

    // Post actions to clean up the workspace and print success/failure messages
    post {
        always {
            echo 'Cleaning up workspace...'
            cleanWs()
        }
        success {
            echo 'Mario deployment complete'
        }
        failure {
            echo 'Deployment failed. Check logs for interface details.'
        }
    }
}

